### ISSUE TITLE
Does not handle ESRI "MultiPolygons"

### ISSUE THREAD

**Issue by gmaclennan** [openaddresses/esri-dump#19]
It looks like ESRI JSON has no MultiPolygon object. MultiPolygons are of type "esriGeometryPolygon". The geometry object has an array of rings. The only way it seems to distinguish a MultiPolygon from a hole inside a polygon is a manual check for overlap, as used by the Terraformer library: https://github.com/Esri/terraformer-arcgis-parser/blob/master/terraformer-arcgis-parser.js#L170

I had no idea how big a headache converting an ESRI JSON file to a usable format would be...

**Comment by ingalls** [comment]
Merged #20 , thanks for the PR!
