### ISSUE TITLE
Premature file end, incomplete collection

### ISSUE THREAD

**Issue by geobrando** [openaddresses/esri-dump#28]
Testing a [source](https://github.com/openaddresses/openaddresses/blob/839fba4480145573ea02b092b4cb49bafac1f964/sources/us/sc/lexington.json) from the command line and the geojson ends before all of the records download or stream, leaving an invalid output file.

```
esri-dump http://maps.lex-co.com/arcgis/rest/services/AddressPts/MapServer/0 > output.geojson
```

Tested twice, and after adding a closing `]}` I found incomplete collections and a different number of features.  Click on the image to enlarge and see the record counts and the holes in the layer

![2015-09-09-121617_1920x1054_scrot](https://cloud.githubusercontent.com/assets/1833870/9767520/9bcc3ac4-56ec-11e5-9292-6f1545211b3d.png)

**Comment by iandees** [comment]
The code in this report isn't used by machine to fetch esri sources.
There's code within machine's cache.py to do that.

Not that this invalidates the bug...

**Comment by geobrando** [comment]
Good point.  Source says skip so I assumed Machine's code also resulted in an error of some kind (there was no note).  Going to remove the skip and see how Machine handles it.

**Comment by ingalls** [comment]
Closing as stale/in-actionable.
