### ISSUE TITLE
ECONNRESET error from MapServer

### ISSUE THREAD

**Issue by joehand** [openaddresses/esri-dump#33]
I keep getting `ECONNRESET` errors on [MapServer export](( https://www.portlandmaps.com/arcgis/rest/services/Public/COP_OpenData/MapServer/112)). Having some trouble debugging it, maybe y'all have some ideas.  

I have a request going to a MapServer that is doing the following:

* Makes ~20 requests that get `exceededTransferLimit`
* Makes 1 successful request to get the data (got 136 features)
* Makes next request to get next bounding box and errors with `ECONNRESET` 

I added some logs to see what was happening, this is the last request information:

```
previous request got 136 features at url:
https://www.portlandmaps.com/arcgis/rest/services/Public/COP_OpenData/MapServer/112/query?geometry=-13648750.261287501%2C5711764.146687499%2C-13646212.67600625%2C5713953.024956249&geometryType=esriGeometryEnvelope&spatialRel=esriSpatialRelIntersects&geometryPrecision=7&returnGeometry=true&outSR=4326&outFields=%2A&f=json

NEW REQUEST (total request count: 21)

REQUEST URL:
https://www.portlandmaps.com/arcgis/rest/services/Public/COP_OpenData/MapServer/112/query?geometry=-13674126.1141%2C5698630.877075%2C-13663975.772975001%2C5707386.390149999&geometryType=esriGeometryEnvelope&spatialRel=esriSpatialRelIntersects&geometryPrecision=7&returnGeometry=true&outSR=4326&outFields=*&f=json 

request error { Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TLSWrap.onread (net.js:569:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
```

It seems like maybe the bounding box is still too large. Its getting 136 features on the first request but it is taking a long time (though increasing the timeout didn't fix it). 

I'll keep debugging later but let me know if anything ideas pop up.

**Comment by iandees** [comment]
This node version of the esri scraper isn't quite as well-maintained as [the Python version over here](https://github.com/openaddresses/pyesridump). If you're comfortable with Python you might try that one?

**Comment by joehand** [comment]
> This node version of the esri scraper isn't quite as well-maintained as the Python version over here. If you're comfortable with Python you might try that one?

Thanks! that one seems to be working for this layer, I'll see if I can use that instead.

**Comment by joehand** [comment]
Update: went to the python module and got the same error on other datasets, so it may be a server or common issue. I still need to do some more debugging on both sides, js + python modules. =)
