### ISSUE TITLE
Duplicate OBJECTIDs not returned

### ISSUE THREAD

**Issue by stenuto** [openaddresses/esri-dump#35]
There are many datasets that contain duplicate object IDs. Here is an example feature layer: `https://maps.deschutes.org/arcgis/rest/services/Dial2_Taxlots/MapServer/0`

There are 10 features with an `Taxlot_Assessor_Account.OBJECTID` of `7313`:  [JSON Results](https://maps.deschutes.org/arcgis/rest/services/Dial2_Taxlots/MapServer/0/query?f=geojson&where=Taxlot_Assessor_Account.OBJECTID=7313)

EsriDump is only returning 1. How can I change the default behavior so that EsriDump pulls _all_ of the features?

**Comment by iandees** [comment]
I only see one entry in your JSON results link there.

At a high level, my understanding is that the "OIDType" field represents the "primary key" of the underlying database table and must be unique across the whole dataset.

**Comment by ingalls** [comment]
This is my understanding as well, also not seeing a duplicate. Going to close unless a test case is provided that shows this behaviour.
