### ISSUE TITLE
Does the CLI accept arbitrary headers?

### ISSUE THREAD

**Issue by rbrtmrtn** [openaddresses/esri-dump#36]
Hello! It looks like the API [takes](https://github.com/openaddresses/esri-dump/blob/master/lib/fetch.ts#L17) will include any additional HTTP headers. Does the CLI work this way, too?

**Comment by ingalls** [comment]
@rbrtmrtn I'm afraid it doesn't. I don't personally use the CLI much so I haven't put to much work to keep it in parity. If you throw together a PR happy to review and get it merged.

**Comment by iandees** [comment]
[pyesridump](https://github.com/openaddresses/pyesridump) does.

**Comment by ingalls** [comment]
Highly recomment using PyEsriDump over this library for CLI use. I primarily use this library on projects where there is an existing node environment and I don't want to shell out to python. It consistently lags behind the performance of PyEsriDump.

**Comment by rbrtmrtn** [comment]
I appreciate the heads up on that @ingalls. I think it might help to have some sort of banner on the README to that effect. I put quite a bit of time into getting to know this library and adapting it to accept headers (it looks like you beat me to the punch on the PR, no worries 😄). But if it's not a comparable tool or officially recommended, at least for CLI use, that seems like an important flag for other newcomers.
